<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Settings
    |--------------------------------------------------------------------------
    |
    | Set some default values
    |
    */

    'font_dir' => storage_path('fonts/'),
    'font_cache' => storage_path('fonts/'),
    'temp_dir' => sys_get_temp_dir(),
    'chroot' => realpath(base_path()),
    'enable_font_subsetting' => true,
    'enable_php' => false,
    'enable_javascript' => false,
    'enable_remote' => true,
    'enable_html5_parser' => true,

    /*
    |--------------------------------------------------------------------------
    | Default paper size and orientation
    |--------------------------------------------------------------------------
    */

    'format' => 'A4',
    'orientation' => 'portrait',

    /*
    |--------------------------------------------------------------------------
    | Default font
    |--------------------------------------------------------------------------
    */

    'default_font' => 'DejaVu Sans',

    /*
    |--------------------------------------------------------------------------
    | Image DPI setting
    |--------------------------------------------------------------------------
    */

    'dpi' => 96,

    /*
    |--------------------------------------------------------------------------
    | Enable inline PHP
    |--------------------------------------------------------------------------
    */

    'enable_php' => false,

    /*
    |--------------------------------------------------------------------------
    | Enable inline Javascript
    |--------------------------------------------------------------------------
    */

    'enable_javascript' => false,

    /*
    |--------------------------------------------------------------------------
    | Restricted settings
    |--------------------------------------------------------------------------
    |
    | Set the security settings for PDF generation
    |
    */

    'enable_remote' => true,
    'enable_html5_parser' => true,
    'isRemoteEnabled' => true,
    'isPhpEnabled' => false,
    'isJavascriptEnabled' => false,
    'isHtml5ParserEnabled' => true,

    /*
    |--------------------------------------------------------------------------
    | HTTP context options
    |--------------------------------------------------------------------------
    |
    | Set the HTTP context options for file_get_contents
    |
    */

    'http_context' => [
        'ssl' => [
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Watermark settings
    |--------------------------------------------------------------------------
    |
    | Set default watermark settings
    |
    */

    'watermark' => [
        'enabled' => false,
        'text' => 'CONFIDENTIAL',
        'opacity' => 0.1,
        'font' => 'DejaVu Sans',
        'size' => 72,
        'color' => '#cccccc',
        'angle' => -45,
        'position' => 'center',
    ],

    /*
    |--------------------------------------------------------------------------
    | Header and Footer settings
    |--------------------------------------------------------------------------
    |
    | Set default header and footer settings
    |
    */

    'header' => [
        'enabled' => true,
        'text' => 'MyArtikel Export',
        'font' => 'DejaVu Sans',
        'size' => 10,
        'color' => '#666666',
        'line' => true,
    ],

    'footer' => [
        'enabled' => true,
        'text' => 'Generated by MyArtikel',
        'font' => 'DejaVu Sans',
        'size' => 10,
        'color' => '#666666',
        'line' => true,
        'page_numbers' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Font settings
    |--------------------------------------------------------------------------
    |
    | Set font settings for better typography
    |
    */

    'fonts' => [
        'default' => 'DejaVu Sans',
        'serif' => 'DejaVu Serif',
        'sans-serif' => 'DejaVu Sans',
        'monospace' => 'DejaVu Sans Mono',
        'heading' => 'DejaVu Sans',
        'body' => 'DejaVu Sans',
    ],

    /*
    |--------------------------------------------------------------------------
    | Typography settings
    |--------------------------------------------------------------------------
    |
    | Set typography settings for better readability
    |
    */

    'typography' => [
        'line_height' => 1.6,
        'paragraph_spacing' => 1.2,
        'margin_top' => 20,
        'margin_right' => 15,
        'margin_bottom' => 20,
        'margin_left' => 15,
        'font_size' => [
            'body' => 12,
            'heading1' => 24,
            'heading2' => 20,
            'heading3' => 16,
            'heading4' => 14,
            'small' => 10,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Page break settings
    |--------------------------------------------------------------------------
    |
    | Set page break settings for better layout
    |
    */

    'page_breaks' => [
        'avoid_break_inside' => [
            'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
            'img', 'table', 'blockquote', '.avoid-break',
        ],
        'always_break_before' => [
            'h1', '.page-break',
        ],
        'avoid_break_after' => [
            'h1', 'h2', 'h3',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Image settings
    |--------------------------------------------------------------------------
    |
    | Set image settings for better quality
    |
    */

    'images' => [
        'quality' => 85,
        'max_width' => 1200,
        'max_height' => 1200,
        'resize' => true,
        'compression' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Performance settings
    |--------------------------------------------------------------------------
    |
    | Set performance settings for faster generation
    |
    */

    'performance' => [
        'enable_font_caching' => true,
        'enable_image_caching' => true,
        'enable_css_caching' => true,
        'memory_limit' => '256M',
        'max_execution_time' => 300,
        'enable_compression' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Security settings
    |--------------------------------------------------------------------------
    |
    | Set security settings for safe PDF generation
    |
    */

    'security' => [
        'enable_remote' => true,
        'enable_php' => false,
        'enable_javascript' => false,
        'allowed_protocols' => ['http', 'https', 'file'],
        'blocked_domains' => [],
        'allowed_domains' => ['*'],
    ],

];
