<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Str;

class Tag extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'slug',
        'description',
        'color',
        'user_id',
        'type',
        'is_auto_generated',
        'usage_count',
        'metadata',
        'articles_count',
    ];

    protected $casts = [
        'articles_count' => 'integer',
        'usage_count' => 'integer',
        'is_auto_generated' => 'boolean',
        'metadata' => 'array',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($tag) {
            if (empty($tag->slug)) {
                $tag->slug = Str::slug($tag->name);
            }

            // Ensure unique slug per user
            if ($tag->user_id) {
                $originalSlug = $tag->slug;
                $count = 1;

                while (static::where('user_id', $tag->user_id)
                    ->where('slug', $tag->slug)
                    ->where('id', '!=', $tag->id ?? 0)
                    ->exists()) {
                    $tag->slug = $originalSlug.'-'.$count++;
                }
            }
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function articles(): BelongsToMany
    {
        return $this->belongsToMany(Article::class);
    }

    public function scopeForUser($query, $userId)
    {
        return $query->where('user_id', $userId);
    }

    public function scopeSystemTags($query)
    {
        return $query->whereNull('user_id');
    }

    public function scopeCustomTags($query, $userId)
    {
        return $query->where('user_id', $userId)->where('type', 'custom');
    }

    public function scopeAutoGenerated($query, $userId)
    {
        return $query->where('user_id', $userId)->where('is_auto_generated', true);
    }

    public function incrementUsage()
    {
        $this->increment('usage_count');
    }

    public function decrementUsage()
    {
        $this->decrement('usage_count');
    }
}
